//------------------------------------------------
//--- 010 Editor v12.0.1 Include File
//
//      File: UtilityFunctions.inc
//   Authors: 
//   Version: 
//   Purpose: 
//  Category: 
// File Mask: 
//  ID Bytes: 
//   History: 
//------------------------------------------------
#ifndef _USEFULTYPES_INC_

#define _USEFULTYPES_INC_

typedef ubyte HEXBYTE <format=hex>;

typedef ushort HEXWORD <format=hex>;

typedef uint32 HEXLONG <format=hex>;

typedef int COLOR010 <format=hex>;

#endif // _USEFULTYPES_INC_